spring:
  cloud:
    gateway:
      routes:
      - id: backend
        uri: http://localhost:8081
        predicates:
        - Path=/api/**
        filters:
        - RewritePath=/api/?(?<segment>.*), /$\{segment}
      - id: frontend
        uri: http://localhost:4173
        predicates:
        - Path=/**
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
        add-additional-paths: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - gateway
