debug: true
spring:
  cloud:
    gateway:
      routes:
      - id: backend
        uri: http://localhost:8081
        predicates:
        - Path=/api/**
      - id: frontend
        uri: http://localhost:5173
        predicates:
        - Path=/**
management:
  endpoints:
    web:
      exposure:
        include: gateway

