apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-prod
spec:
  acme:
    email: hello@samsanders.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - selector:
        dnsZones:
          - "eks.samsanders.dev"
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z001793829CV21MFAAFC7
          role: arn:aws:iam::634611482126:role/AmazonEKSCertManagerRole