apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: gateway-reference
data:
  application-cloud.yaml: |
    spring:
      cloud:
        gateway:
          routes:
          - id: backend
            uri: http://backend:8080
            predicates:
            - Path=/api/**
            filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
          - id: frontend
            uri: http://frontend:8080
            predicates:
            - Path=/**