apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: gateway-reference
  labels:
    system: gateway-reference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        system: gateway-reference
    spec:
      containers:
      - name: backend
        image: ssanders0/ptp-backend:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 256M
            cpu: 100m
          limits:
            memory: 1G
            cpu: 1
