apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: gateway-reference
  labels:
    system: gateway-reference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        system: gateway-reference
    spec:
      containers:
      - name: frontend
        image: ssanders0/ptp-frontend:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: 256M
            cpu: 100m
          limits:
            memory: 1G
            cpu: 1
